### PR TITLE
Pull upstream changes

### PR DESCRIPTION
**Pull request by eric-wieser**
Hi!

@utensil made me aware you're doing some great work here writing examples and tests.

Unfortunately, they're diverging from the new home of `galgebra`, pygae/galgebra.

This PR is just showing you the list of commits you'd get if you pulled locally. There'll be some conflicts, so I don't recommend attempting this through the web interface, but this seemed like a good way to start the conversation.

### CODE REVIEW

**Comment by meuns** [comment]
I will merge pygae/galgebra in a near future but I can't find a few hours of free time nowadays. Be sure I will update you when it's done.

**Comment by meuns** [comment]
I merged pygae/master. There is some fixes to do in my tests.

**Comment by eric-wieser** [comment]
Thanks!

It seems that thanks to @abrombo deleting his @brombo account, this repo has switched from being a fork of `brombo/galgebra` to being the root repository from which all forks (including `pygae/galgebra`) have come.

In my opinion, your repository should be listed as a fork of ours. Do you agree?

If so, github support has the power to switch them - @mattamorphic wanted me to get your approval to do so first.

If not, please let me know anyway - and we'll sort something else out our end

**Comment by meuns** [comment]
My repository is just for hacking things. Feel free to change this.

**Pull request merged**
